/* Minijuego 1: Plano Cartesiano y Traslación */
const PlanoGame = {
  gridSize: 8,
  currentMode: 'point', // 'point' or 'translation'
  targetPoint: { x: 0, y: 0 },
  currentShape: null,
  translationVector: { dx: 0, dy: 0 },
  score: 0,
  questionsAnswered: 0,
  maxQuestions: 5,
  isAnswered: false,

  init(container) {
    this.score = 0;
    this.questionsAnswered = 0;
    this.isAnswered = false;
    this.renderLayout(container);
    this.nextQuestion();
  },

  renderLayout(container) {
    container.innerHTML = `
      <div class="game-container">
        <div class="game-score-bar">
          <span>🎯 Tema 1: Plano Cartesiano y Traslación</span>
          <span>Puntos: <strong id="plano-score">0</strong> / 5</span>
        </div>
        
        <div class="question-box pop-animation" id="plano-instruction">
          ¡Cargando pregunta...!
        </div>

        <div class="game-canvas-wrapper">
          <svg id="plano-svg" width="380" height="380" viewBox="-30 -30 380 380" style="background: white; border-radius: 12px; cursor: pointer;">
            <!-- Grid generated by JS -->
          </svg>
        </div>

        <div id="plano-controls" style="display: flex; gap: 10px; flex-wrap: wrap; justify-content: center;">
          <!-- Controls inserted dynamically -->
        </div>

        <div id="plano-feedback" style="font-weight: 700; font-size: 1.2rem; min-height: 30px; text-align: center;"></div>
      </div>
    `;

    document.getElementById('plano-svg').addEventListener('click', (e) => this.handleSvgClick(e));
  },

  nextQuestion() {
    this.isAnswered = false;
    if (this.questionsAnswered >= this.maxQuestions) {
      this.finishGame();
      return;
    }

    const feedback = document.getElementById('plano-feedback');
    if (feedback) feedback.innerText = '';
    
    // Alternate modes
    this.currentMode = (this.questionsAnswered % 2 === 0) ? 'point' : 'translation';

    if (this.currentMode === 'point') {
      this.targetPoint = {
        x: Math.floor(Math.random() * (this.gridSize - 1)) + 1,
        y: Math.floor(Math.random() * (this.gridSize - 1)) + 1
      };
      document.getElementById('plano-instruction').innerHTML = 
        `🌟 Ubica la estrella en la coordenada: <strong>(${this.targetPoint.x}, ${this.targetPoint.y})</strong>.<br><small>(Haz clic directo en la intersección de la cuadrícula)</small>`;
      document.getElementById('plano-controls').innerHTML = '';
      this.drawGrid();
    } else {
      // Shape translation mode
      const x0 = Math.floor(Math.random() * 3) + 1;
      const y0 = Math.floor(Math.random() * 3) + 1;
      this.currentShape = [
        { x: x0, y: y0 },
        { x: x0 + 2, y: y0 },
        { x: x0 + 1, y: y0 + 3 }
      ];
      this.translationVector = {
        dx: Math.floor(Math.random() * 3) + 1,
        dy: Math.floor(Math.random() * 3) + 1
      };
      
      document.getElementById('plano-instruction').innerHTML = 
        `📐 <strong>Traslación de Figuras:</strong> Mueve la figura morada <strong>${this.translationVector.dx} unidades a la DERECHA</strong> y <strong>${this.translationVector.dy} unidades ARRIBA</strong>.`;
      
      document.getElementById('plano-controls').innerHTML = `
        <div style="display: flex; flex-direction: column; gap: 8px; align-items: center;">
          <p>Ajusta el traslado y presiona <strong>Comprobar</strong>:</p>
          <div style="display: flex; gap: 14px; align-items: center;">
            <label><strong>Horizontal (Derecha):</strong> <input type="number" id="input-dx" class="input-num" min="0" max="6" value="0"></label>
            <label><strong>Vertical (Arriba):</strong> <input type="number" id="input-dy" class="input-num" min="0" max="6" value="0"></label>
          </div>
          <button class="btn-action" id="btn-check-trans" onclick="PlanoGame.checkTranslation()">✨ Comprobar Traslación</button>
        </div>
      `;
      this.drawGrid();
      this.drawShape(this.currentShape, '#6C5CE7', 'Original');
    }
  },

  drawGrid() {
    const svg = document.getElementById('plano-svg');
    if (!svg) return;
    svg.innerHTML = '';
    const step = 320 / this.gridSize;

    // Grid lines
    for (let i = 0; i <= this.gridSize; i++) {
      const pos = i * step;
      // Vertical line
      svg.appendChild(this.createSvgElem('line', { x1: pos, y1: 0, x2: pos, y2: 320, stroke: '#E2E8F0', 'stroke-width': 2 }));
      // Horizontal line
      svg.appendChild(this.createSvgElem('line', { x1: 0, y1: 320 - pos, x2: 320, y2: 320 - pos, stroke: '#E2E8F0', 'stroke-width': 2 }));
      
      // X labels
      const txtX = this.createSvgElem('text', { x: pos, y: 342, 'font-size': 14, 'text-anchor': 'middle', fill: '#636E72', 'font-weight': 'bold' });
      txtX.textContent = i;
      svg.appendChild(txtX);

      // Y labels
      const txtY = this.createSvgElem('text', { x: -14, y: 320 - pos + 5, 'font-size': 14, 'text-anchor': 'middle', fill: '#636E72', 'font-weight': 'bold' });
      txtY.textContent = i;
      svg.appendChild(txtY);
    }

    // Axes
    svg.appendChild(this.createSvgElem('line', { x1: 0, y1: 0, x2: 0, y2: 320, stroke: '#2D3436', 'stroke-width': 3 }));
    svg.appendChild(this.createSvgElem('line', { x1: 0, y1: 320, x2: 320, y2: 320, stroke: '#2D3436', 'stroke-width': 3 }));
  },

  drawShape(points, color, label) {
    const svg = document.getElementById('plano-svg');
    const step = 320 / this.gridSize;
    const ptsString = points.map(p => `${p.x * step},${320 - p.y * step}`).join(' ');

    const polygon = this.createSvgElem('polygon', {
      points: ptsString,
      fill: color,
      'fill-opacity': 0.35,
      stroke: color,
      'stroke-width': 3,
      'stroke-dasharray': label === 'Original' ? '4' : 'none'
    });
    svg.appendChild(polygon);

    // Draw vertices
    points.forEach((p, idx) => {
      const circle = this.createSvgElem('circle', {
        cx: p.x * step,
        cy: 320 - p.y * step,
        r: 6,
        fill: color
      });
      svg.appendChild(circle);
    });
  },

  handleSvgClick(e) {
    if (this.isAnswered || this.currentMode !== 'point') return;

    const svg = document.getElementById('plano-svg');
    const rect = svg.getBoundingClientRect();
    const clickX = e.clientX - rect.left - 30; // adjusting margin
    const clickY = e.clientY - rect.top - 30;

    const step = 320 / this.gridSize;
    const gridX = Math.round(clickX / step);
    const gridY = Math.round((320 - clickY) / step);

    if (gridX < 0 || gridX > this.gridSize || gridY < 0 || gridY > this.gridSize) return;

    // Draw clicked dot
    this.drawGrid();
    const circle = this.createSvgElem('circle', {
      cx: gridX * step,
      cy: 320 - gridY * step,
      r: 10,
      fill: (gridX === this.targetPoint.x && gridY === this.targetPoint.y) ? '#00B894' : '#FF7675'
    });
    svg.appendChild(circle);

    const feedback = document.getElementById('plano-feedback');
    if (gridX === this.targetPoint.x && gridY === this.targetPoint.y) {
      this.isAnswered = true;
      sounds.play('correct');
      feedback.style.color = '#00B894';
      feedback.innerHTML = `🎉 ¡Excelente Lu! Marcaste (${gridX}, ${gridY}) correctamente.`;
      this.score++;
      document.getElementById('plano-score').innerText = this.score;
      this.questionsAnswered++;
      setTimeout(() => this.nextQuestion(), 1500);
    } else {
      sounds.play('wrong');
      feedback.style.color = '#FF7675';
      feedback.innerHTML = `❌ Marcaste (${gridX}, ${gridY}). Recuerda: primero buscas en el eje horizontal X y luego subes en el Y. ¡Inténtalo de nuevo!`;
    }
  },

  checkTranslation() {
    if (this.isAnswered) return;

    const inputDx = parseInt(document.getElementById('input-dx').value) || 0;
    const inputDy = parseInt(document.getElementById('input-dy').value) || 0;

    const feedback = document.getElementById('plano-feedback');

    if (inputDx === this.translationVector.dx && inputDy === this.translationVector.dy) {
      this.isAnswered = true;
      const btn = document.getElementById('btn-check-trans');
      if (btn) btn.disabled = true;

      // Draw translated shape in green
      const translated = this.currentShape.map(p => ({
        x: p.x + inputDx,
        y: p.y + inputDy
      }));
      this.drawShape(translated, '#00B894', 'Trasladada');

      sounds.play('correct');
      feedback.style.color = '#00B894';
      feedback.innerHTML = `🎉 ¡Perfecto! La figura se trasladó correctamente ${inputDx} a la derecha y ${inputDy} arriba.`;
      this.score++;
      document.getElementById('plano-score').innerText = this.score;
      this.questionsAnswered++;
      setTimeout(() => this.nextQuestion(), 1800);
    } else {
      sounds.play('wrong');
      feedback.style.color = '#FF7675';
      feedback.innerHTML = `❌ Revisa los valores. Necesitabas trasladar ${this.translationVector.dx} a la derecha y ${this.translationVector.dy} arriba.`;
    }
  },

  finishGame() {
    const starsEarned = this.score >= 4 ? 3 : (this.score >= 2 ? 2 : 1);
    App.saveStars('plano', starsEarned);
    sounds.play('fanfare');
    
    document.getElementById('plano-instruction').innerHTML = `
      🏆 <strong>¡Juego Completado!</strong><br>
      Obtuviste ${this.score} de 5 puntos y ganaste <strong>${'⭐'.repeat(starsEarned)}</strong> Estrellas.
    `;
    document.getElementById('plano-controls').innerHTML = `
      <button class="btn-action" onclick="PlanoGame.init(document.getElementById('game-area'))">🔄 Jugar de nuevo</button>
    `;
  },

  createSvgElem(type, attrs) {
    const elem = document.createElementNS('http://www.w3.org/2000/svg', type);
    for (let k in attrs) {
      elem.setAttribute(k, attrs[k]);
    }
    return elem;
  }
};
